version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:448704111492:task-definition/swiggy:2"
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000

