version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 448704111492.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - docker build -t 448704111492.dkr.ecr.ap-south-1.amazonaws.com/swiggy:latest .
      - docker push 448704111492.dkr.ecr.ap-south-1.amazonaws.com/swiggy:latest

post_build:
  commands:
    - echo "Build completed successfully!"
    - aws ses send-email \
        --from "sangeetashinde.gaikwad@gmail.com" \
        --to "jyotiraul74@gmail.com" \
        --subject "CodeBuild Status: $CODEBUILD_BUILD_ID" \
        --text "Build status: $CODEBUILD_BUILD_STATUS" \
        --region "ap-south-1"

artifacts:
  files:
    - appspec.yaml
